baseURL = 'https://yuk1pedia.github.io/'
languageCode = 'zh-cn'
title = "YUKIPEDIA's blog"
theme = ["PaperMod"]

[params]
  defaultTheme = "auto"
  
  [params.homeInfoParams]
    Title = "Welcome!"
    Content = "Can be Info, links, about..."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/YUK1PEDIA"
  

[[menu.main]]
  name = "Learning Notes"
  url = "/Learning Notes"
  weight = 1

[[menu.main]]
  name = "Algorithm"
  url = "/Algorithm"
  weight = 2