baseURL = 'https://yuk1pedia.github.io/'
languageCode = 'zh-cn'
title = "YUKIPEDIA's blog"
theme = ["PaperMod"]

[params]
  defaultTheme = "auto"
  
  # 使用标准表格格式替代内联表格
  [params.homeInfoParams]
    Title = "Hello, I'm YUKIPEDIA. Welcome to my blog"

[[menu.main]]
  name = "Learning Notes"
  url = "/Learning Notes"
  weight = 1